version: '3.8'
services:
  client:
    build:
      context: ./client
    ports:
      - 3000:3000
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm run dev
    depends_on:
      - server
      - mongo

  server:
    build:
      context: ./server
    ports:
      - 5000:5000
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - MONGO_URI=mongodb://mongo:27018/mavens
    command: npm run dev
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - '27018:27017'
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
